### ISSUE TITLE
Upgrade to JUnit5 

### ISSUE THREAD

**Issue by volkodavs** [matchbook-technology/matchbook-sdk#70]
junit5 provide a lot of new functionality that will be useful for improving our tests cases

**Comment by sowmiyamuthuraman** [comment]
can i work on this?

**Comment by volkodavs** [comment]
yes, you can. 
You need to open a pull request with your changes

**Comment by alessandrodalbello** [comment]
@volkodavs @sowmiyamuthuraman can we just include this with #63? Considering there are basically no unit tests at the moment, it would make much more sense to write tests using JUnit 5 straightaway.

I'll add the ticket in the current milestone kanban board. Also I'll mark this one as duplicate if you agree with that.

**Comment by alessandrodalbello** [comment]
@sowmiyamuthuraman A decision has been taken to keep the tickets separate, this one to add the JUnit5 dependency and convert the existing unit tests (a couple of classes there), and another one to reach the 80% code coverage goal. Are you planning to work on this soon?

**Comment by sowmiyamuthuraman** [comment]
Yeah!
